AnalyticsJS:
  global_name:        ga                  # set a tracker function name (defaults to "ga")
  compress_js:        true                # compress inline JavaScript
  track_links:        true                # disable external link / asset tracking
  link_category:      "Outgoing Links"    # Outgoing link category name for GA
  email_category:     "Email Links"       # Email link category name for GA
  phone_category:     "Phone Links"       # Phone link category name for GA
  downloads_category: "Downloads"         # Phone link category name for GA
  404_category:       "Page Not Found"    # 404 page category name for GA
  error_category:     "Page Error"        # Error page category (not 404) for GA
